config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root to: "companies#index"
  resources :companies, :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_one_attached :businessplan

  validates :name, presence: true, length: { minimum: 3}
  validate :valid_name?
  validates :cost, presence: true

  def valid_name?
    return name != nil && !name.strip.empty?
  end
end

app/models/member.rb
class Member < ApplicationRecord
  rolify :role_cname => 'Position'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :user
end

app/models/position.rb
class Position < ApplicationRecord
  has_and_belongs_to_many :members, :join_table => :members_positions
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :user_roles, dependent: :destroy
    has_many :users, through: :user_roles
end

app/models/user.rb
class User < ApplicationRecord
    has_many :companies, dependent: :destroy
    has_many :user_roles, dependent: :destroy
    has_many :roles, through: :user_roles

    # Return the full name of the user, to make the code drier
    def full_name
        return "#{first_name} #{last_name}"
    end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :forbidden

    private

    def forbidden
        flash[:alert] = "You are not authorized to perform that action."
        redirect_to request.referrer || root_path
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :authenticate_member!
    before_action :check_auth, except: [:index, :show]
    before_action :set_company, only: [:update, :show, :destroy, :edit]
    before_action :set_users, only: [:new, :edit, :create, :update]

    def index
        @companies = Company.order(:name)
    end

    def show
    end

    def new
        @company = Company.new
    end

    def create
        @company = Company.new(company_params)
        if @company.save
            redirect_to @company
        else
            flash.now[:errors] = @company.errors.full_messages
            render action: 'new'
        end
    end

    def edit
    end

    def update
        if @company.update(company_params)
            redirect_to @company
        else
            flash.now[:errors] = @company.errors.full_messages
            render action: 'edit'
        end
    end

    def destroy
        @company.destroy
        redirect_to companies_path
    end

    private

    def pundit_user
        current_member
    end

    def set_company
        @company = Company.find(params[:id])
    end

    def check_auth
        authorize Company
    end

    def set_users
        @users = User.order(:last_name)
    end

    def company_params
        params.require(:company).permit(:name, :user_id, :businessplan, :cost)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:last_name)
  end

  def show
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_with model: @company, local: true do |f| %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>    
    </p>
    <p>
        <%= f.label :user_id %>
        <%= f.collection_select :user_id, @users, :id, :full_name %>   
    </p>
    <p>
        <%= f.label :cost %>
        <%= f.text_field :cost %>
    </p>
    <p>
        <%= f.label "Business Plan:" %>
        <br>
        <%= f.file_field :businessplan %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render "form" %>

app/views/companies/index.html.erb
<h1>Welcome to the Whale Tank!</h1>

<% if policy(Company).new? %>
    <p><%= link_to "New Company", new_company_path %></p>
<% end %>

<table>
    <tr>
        <th>Name</th>
        <th>Owner</th>
        <th>Cost</th>
        <% if policy(Company).create? || policy(Company).destroy? %>
            <th>Actions</th>
        <% end %>    
    </tr>
    <% @companies.each do |company| %>
        <tr>
            <td><%= link_to company.name, company_path(company) %></td>
            <td><%= company.user.full_name %></td>
            <td><%= company.cost %></td>
            <% if policy(Company).create? || policy(Company).destroy? %>
                <td>
                    <%= link_to "Edit", edit_company_path(company) if policy(Company).edit? %>
                    | 
                    <%= link_to "Delete", company, method: :delete, data: { confirm: "Are you sure you want to remove this company?" } if policy(Company).destroy? %>
                </td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render "form" %>

app/views/companies/show.html.erb
<h2><%= @company.name %></h2>
<h3>Proposed by <%= @company.user.full_name %></h3>
<p><strong>Cost: </strong>$<%= @company.cost %></p>
<%# If a business plan is attached to this company, render the business plan %>
<% if @company.businessplan.attached? %>
    <p><strong>Business Plan:</strong></p>    
    <p><%= cl_image_tag @company.businessplan.key, crop: :scale, width: 300, cloud_name: "marketplace-project" %></p>
<% end %>    
<hr />
<p>
    <%= link_to "<< Back", :back %>
    <% if policy(Company).edit? || policy(Company).destroy? %>
        | 
        <%= link_to "Edit", edit_company_path if policy(@company).edit? %>
        |
        <%= link_to "Delete", @company, method: :delete, data: { confirm: "Are you sure you want to remove this company?" } if policy(Company).destroy? %>
    <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whale Tank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <figure>
        <img src="https://picsum.photos/50" alt="Whale Tank Logo">
        <figcaption>Whale Tank</figcaption>
      </figure>
      <nav>
        <span><%= link_to "Home", root_path %></span>
        <span><%= link_to "Companies", companies_path %></span>
        <span><%= link_to "Users", users_path %></span>
        <span>
          <% if member_signed_in? %>
            <%= current_member.email %>
             |
            <%= link_to "Logout", destroy_member_session_path, method: :delete %>
          <% else %>
            <%= link_to "Login", new_member_session_path %>
             |
            <%= link_to "Sign Up", new_member_registration_path %>
          <% end %>
        </span>
      </nav>
    </header>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if flash[:errors] %>
      <section class="errors">
        <p class="name">The following errors occurred:</p>
        <ul>
          <% flash[:errors].each do |error| %>
            <li><%= error %></li>
          <% end %>  
        </ul>
      </section>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>List Users</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Companies</th>
        <th>Roles</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= link_to user.full_name, user_path(user) %></td>
            <td>
                <%user.companies.each do |company|%>
                    <p><%= link_to company.name, company_path(company) %></p>
                <% end %>
            </td>
            <td><%= user.roles.map { |role| role.name }.join(", ") %></td>
        </tr>
    <% end %>
</table>

app/views/users/show.html.erb
<h2><%= @user.full_name %></h2>
<h3>About:</h3>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt aspernatur alias molestiae reprehenderit sequi voluptatibus a facere sapiente ea quaerat adipisci quod vero nihil, eos minus id deleniti vitae ullam!</p>
<h4><strong>Proposed Companies: </strong></h4>
<p>
    <%@user.companies.each do |company|%>
        <%= link_to company.name, company_path(company) %>
    <% end %>
</p>
<hr>
<p><%= link_to "<< Back", :back %></p>